import "./globals.css";
import { ReactNode } from "react";
import NextAuthProvider from "../components/providers/components/next-auth-provider";
// import { getServerSession } from "next-auth";
// import { OPTIONS } from "../auth";
import SessionWrapper from "../components/layout/SessionWrapper";

export const metadata = {
  title: "Online exam",
  description: "Generated by Samer online exam",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  // const session = await getServerSession(OPTIONS);

  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <SessionWrapper>{children}</SessionWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
