import './globals.css';
import AuthProvider from '@/context/Authprovider';
import SideNav from '../_components/layout/SideNav';
import Search from '../_components/common/Search';

import { ReactNode } from 'react';

export const metadata = {
  title: 'Online exam',
  description: 'Generated by Samer online exam',
};

// Define props for the RootLayout
interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps): Promise<JSX.Element> {
  // Uncomment if session management is required
  // const session = await getServerSession(options);
  // console.log('session from server', session);

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <main className="flex gap-5 p-8 bg-[#FBF9F9]">
            <SideNav />
            <div className="w-full">
              <Search />
              {children}
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
